version: '3.8'

services:
  # server:
  #   container_name: server
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres
  #     - redis
  #   environment:
  #     - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/mydatabase
  #     - REDIS_URL=redis://redis:6379
  #   networks:
  #     - my-network
  #   env_file:
  #     - ./server/.env

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network
    env_file:
      - ./server/.env

  redis:
    container_name: redis
    image: redis:latest
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - my-network

volumes:
  postgres-data:

networks:
  my-network:
